apiVersion: v1
kind: Pod
metadata:
  name: simple-nginx-pod
  namespace: base-namespace
  labels:
    app: nginx
    author: saikat
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
