apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: base-namespace
  labels:
    app: demo
spec:
  containers:
    # First container (main application)
    - name: nginx-container
      image: nginx:alpine
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
      imagePullPolicy: IfNotPresent

    
    # Second container (sidecar)
    - name: busybox-container
      image: busybox:latest
      command: ["/bin/sh", "-c", "sleep infinity"]
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
