apiVersion: v1
kind: Service
metadata:
  name: color-service
  namespace: base-namespace
spec:
  type: ClusterIP
  selector:
    app: color-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000